import { useState } from "react";
import type { Script } from "@/lib/types";
import { SCRIPT_TYPE_LABELS } from "@/lib/constants";

interface ScriptPreviewProps {
  script: Script;
}

export function ScriptPreview({ script }: ScriptPreviewProps) {
  const [activeTab, setActiveTab] = useState<"summary" | "yaml">("summary");

  const yamlString = toSimpleYaml(script);

  const handleDownload = () => {
    const blob = new Blob([yamlString], { type: "text/yaml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${script.meta.title || "script"}.yaml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Tabs */}
      <div className="flex items-center justify-between">
        <div className="flex gap-1 rounded-lg bg-muted p-1">
          <button
            onClick={() => setActiveTab("summary")}
            className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
              activeTab === "summary"
                ? "bg-background shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            摘要
          </button>
          <button
            onClick={() => setActiveTab("yaml")}
            className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
              activeTab === "yaml"
                ? "bg-background shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            YAML 预览
          </button>
        </div>
        <button
          onClick={handleDownload}
          className="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
        >
          ⬇ 下载 YAML
        </button>
      </div>

      {/* Content */}
      {activeTab === "summary" ? (
        <SummaryView script={script} />
      ) : (
        <pre className="max-h-[60vh] overflow-auto rounded-lg border bg-muted/30 p-4 text-xs leading-relaxed">
          {yamlString}
        </pre>
      )}
    </div>
  );
}

function SummaryView({ script }: { script: Script }) {
  const report = script.adaptation_report!;
  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
      <StatCard label="剧本类型" value={SCRIPT_TYPE_LABELS[script.meta.script_type] || script.meta.script_type} />
      <StatCard label="场景数" value={String(report.total_scenes)} />
      <StatCard label="人物数" value={String(script.characters.length)} />
      <StatCard label="对白行数" value={String(report.total_dialogue_lines)} />
      <div className="col-span-full rounded-lg border p-4">
        <h4 className="text-sm font-medium mb-1">改编摘要</h4>
        <p className="text-xs text-muted-foreground">{report.summary}</p>
      </div>
      <div className="col-span-full">
        <h4 className="text-sm font-medium mb-2">场景列表</h4>
        <div className="space-y-1">
          {script.scenes.map((scene) => (
            <div key={scene.id} className="flex items-center justify-between rounded bg-muted/50 px-3 py-1.5 text-xs">
              <span className="font-medium">{scene.heading}</span>
              <span className="text-muted-foreground">{scene.summary || scene.id}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border p-3 text-center">
      <div className="text-2xl font-bold">{value}</div>
      <div className="text-xs text-muted-foreground">{label}</div>
    </div>
  );
}

/** MVP simple YAML serializer — will be replaced with js-yaml in round 2 */
function toSimpleYaml(script: Script): string {
  const lines: string[] = [];

  lines.push(`# ${script.meta.title}`);
  lines.push(`# Generated by ${script.meta.generated_by}`);
  lines.push(`# ${script.meta.generated_at}`);
  lines.push("");
  lines.push("meta:");
  lines.push(`  title: "${script.meta.title}"`);
  lines.push(`  script_type: ${script.meta.script_type}`);
  lines.push(`  source_title: "${script.meta.source_title}"`);
  lines.push(`  language: ${script.meta.language}`);
  lines.push(`  version: "${script.meta.version}"`);
  lines.push(`  generated_by: "${script.meta.generated_by}"`);
  lines.push(`  generated_at: "${script.meta.generated_at}"`);

  lines.push("");
  lines.push("characters:");
  for (const char of script.characters) {
    lines.push(`  - id: ${char.id}`);
    lines.push(`    name: "${char.name}"`);
    lines.push(`    role: ${char.role}`);
    lines.push(`    traits:`);
    for (const t of char.traits) {
      lines.push(`      - "${t}"`);
    }
    if (char.arc) lines.push(`    arc: "${char.arc}"`);
  }

  lines.push("");
  lines.push("structure:");
  const structure = script.structure;
  switch (structure.type) {
    case "movie":
      lines.push(`  type: movie`);
      lines.push("  acts:");
      for (const act of structure.acts) {
        lines.push(`    - act: ${act.act}`);
        if (act.title) lines.push(`      title: "${act.title}"`);
        lines.push(`      scene_ids:`);
        for (const sid of act.scene_ids || []) {
          lines.push(`        - ${sid}`);
        }
      }
      break;
    case "tv_series":
      lines.push(`  type: tv_series`);
      lines.push("  seasons:");
      for (const season of structure.seasons) {
        lines.push(`    - season: ${season.season}`);
        lines.push("      episodes:");
        for (const ep of season.episodes) {
          lines.push(`        - episode: ${ep.episode}`);
          if (ep.title) lines.push(`          title: "${ep.title}"`);
          lines.push(`          scene_ids:`);
          for (const sid of ep.scene_ids || []) {
            lines.push(`            - ${sid}`);
          }
        }
      }
      break;
    case "short_drama":
      lines.push(`  type: short_drama`);
      lines.push("  episodes:");
      for (const ep of structure.episodes) {
        lines.push(`    - episode: ${ep.episode}`);
        if (ep.title) lines.push(`      title: "${ep.title}"`);
        lines.push(`      scene_ids:`);
        for (const sid of ep.scene_ids || []) {
          lines.push(`        - ${sid}`);
        }
      }
      break;
  }

  lines.push("");
  lines.push("scenes:");
  for (const scene of script.scenes) {
    lines.push(`  - id: ${scene.id}`);
    lines.push(`    heading: "${scene.heading}"`);
    if (scene.summary) lines.push(`    summary: "${scene.summary}"`);
    lines.push("    content:");
    for (const block of scene.content) {
      lines.push(`      - type: ${block.type}`);
      if (block.type === "action" || block.type === "dialogue") {
        const text = "text" in block ? block.text : "line" in block ? block.line : "";
        lines.push(`        text: "${(text as string).slice(0, 100)}"`);
      }
      if ("source_ref" in block && block.source_ref) {
        lines.push(`        source_ref: "${block.source_ref}"`);
      }
    }
  }

  if (script.adaptation_report) {
    lines.push("");
    lines.push("adaptation_report:");
    lines.push(`  total_scenes: ${script.adaptation_report.total_scenes}`);
    lines.push(`  total_characters: ${script.adaptation_report.total_characters}`);
    lines.push(`  total_dialogue_lines: ${script.adaptation_report.total_dialogue_lines}`);
    lines.push(`  summary: "${script.adaptation_report.summary}"`);
  }

  return lines.join("\n");
}
