// ============================================================
// Fountain Export (Frontend)
// Converts Script object to Fountain screenplay format
// Ported from backend/src/export/fountain.ts
//
// Fountain is the open standard for screenplay markup,
// compatible with Final Draft, Fade In, Highland, etc.
// ============================================================

import type { Script, Scene, ContentBlock } from "./types";

/**
 * Convert a Script object to Fountain markup string.
 */
export function toFountain(script: Script): string {
  const lines: string[] = [];

  // Title page
  lines.push(`Title: ${script.meta.title}`);
  lines.push(`Source: ${script.meta.source_title}`);
  if (script.meta.source_author) {
    lines.push(`Author: ${script.meta.source_author}`);
  }
  lines.push(`Generated by: ${script.meta.generated_by}`);
  lines.push("");
  lines.push("===");
  lines.push("");

  // Process scenes in order from structure
  const orderedScenes = getOrderedScenes(script);
  for (const scene of orderedScenes) {
    lines.push("");
    lines.push(scene.heading);
    lines.push("");

    for (const block of scene.content) {
      lines.push(...renderContentBlock(block));
    }
  }

  return lines.join("\n");
}

/** Get scenes in structure order */
function getOrderedScenes(script: Script): Scene[] {
  const sceneMap = new Map(script.scenes.map((s) => [s.id, s]));
  const orderedIds: string[] = [];

  const structure = script.structure;
  switch (structure.type) {
    case "movie":
      for (const act of structure.acts) {
        if (act.sequences) {
          for (const seq of act.sequences) {
            orderedIds.push(...seq.scene_ids);
          }
        } else if (act.scene_ids) {
          orderedIds.push(...act.scene_ids);
        }
      }
      break;
    case "tv_series":
      for (const season of structure.seasons) {
        for (const ep of season.episodes) {
          if (ep.cold_open) orderedIds.push(...ep.cold_open.scene_ids);
          if (ep.acts) {
            for (const act of ep.acts) {
              orderedIds.push(...act.scene_ids);
            }
          }
          if (ep.scene_ids) orderedIds.push(...ep.scene_ids);
        }
      }
      break;
    case "short_drama":
      for (const ep of structure.episodes) {
        if (ep.scene_ids) orderedIds.push(...ep.scene_ids);
      }
      break;
  }

  return orderedIds.map((id) => sceneMap.get(id)!).filter(Boolean);
}

/** Render a single content block as Fountain lines */
function renderContentBlock(block: ContentBlock): string[] {
  switch (block.type) {
    case "action":
      return [block.text, ""];

    case "dialogue": {
      const lines = [block.character.toUpperCase()];
      if (block.delivery) {
        lines.push(`(${block.delivery})`);
      }
      lines.push(block.line);
      lines.push("");
      return lines;
    }

    case "voiceover": {
      const lines = [`${block.character.toUpperCase()} (V.O.)`];
      lines.push(block.line);
      lines.push("");
      return lines;
    }

    case "transition":
      return [block.value, ""];

    case "montage": {
      const lines = [block.description, ""];
      for (const beat of block.beats) {
        lines.push(`  - ${beat}`);
      }
      lines.push("");
      return lines;
    }

    case "shot":
      return [`[${block.shot_type} — ${block.subject}]`, block.description, ""];

    default:
      return [];
  }
}
